spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/usersdb
    username: postgres
    password: 12341234
  jpa:
    hibernate:
#      ddl-auto: create
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect